### ISSUE TITLE
When username/Password is wrong on login page then it says "Unauthorized" instead of Wrong username or Password

### ISSUE THREAD

**Issue by numaananjum** [bug-author/coin-bounce#1]
i have followed your course on youtube and pulled the code from here.

i am facing this issue.
When username/Password is wrong on login page then it says "Unauthorized" instead of Wrong username or Password

Can you please find time and  look into please

**Comment by bug-author** [comment]
Thankyou for reporting the issue! Can you provide some more detail? Is the issue on frontend/ UI or in API response or somewhere else? What is the value in `message` key of json response? 

If the value is `"Invalid password"` or `"Invalid username"` then it is working as expected.

I did some quick tests on API and the results are as expected.

### Login for a user with wrong username and wrong password
![image](https://github.com/bug-author/coin-bounce/assets/48406637/e60dd7e9-63f5-4765-8fee-4cdc726a866d)

### Login for a user with correct username but wrong password
![image](https://github.com/bug-author/coin-bounce/assets/48406637/638ff887-6b8a-43ea-9d18-35c5a10bf0f6)

**Comment by numaananjum** [comment]
Thank you for your prompt response. 

I did some testing on API and its working fine. 

![Screenshot 2023-08-08 020627](https://github.com/bug-author/coin-bounce/assets/96891336/07f4e57e-6ad5-40d2-aa53-64418be22fab)


However its the front end that is causing the issue i guess. 

![Screenshot 2023-08-08 020240](https://github.com/bug-author/coin-bounce/assets/96891336/ec3e05cf-bae6-4ab3-8e83-5724de9a136a)


![Screenshot 2023-08-08 020323](https://github.com/bug-author/coin-bounce/assets/96891336/12d8377e-b253-4f16-bf73-0b76d9ffd3fa)


Right after the login API end point is called, a refresh endpoint is being called which return the json. I think this is overriding the login endpoint response. 

Help me out please. 
 
Although i am very grateful to you for your Youtube course but I am completely in dark here because your youtube course did not cover this part of making authentication persistent. I strongly request you to please also cover this part in a youtube video. 
 
Looking forward to your advice on how we can fix this issue. This is my Client project. 

Thanks

**Comment by bug-author** [comment]
I think the same, the previous 401 is being replaced by `/refresh`. Whenever a 401 is issued from backend, a `/refresh` call will be fired. I'll fix the bug.

Also, I do think the course covered persistent authentication when I talked about custom hooks in React for this purpose?!

**Comment by numaananjum** [comment]
Thanks. Looking forward to the fix.

**Comment by bug-author** [comment]
Spent some time in debugging the issue. The issue lies in how `axios` handles API response stuff in recent updates. This needs a proper fix, for which I'll get enough time on weekends only since I have a busy routine on my full time job.

Essentially the status code should be different than `401`. For invalid username it can be `404 - user not found` and for invalid password a suitable status code would be `403 - access forbidden`. However with both of these status codes `axios` will make the JSON response `undefined` at frontend (maybe due to CORS issues or something, haven't had the time to go through it deep enough). (atleast I'm getting undefined at my end, I'm not sure for others). 

I tried status code `500`, `400`, `403` and `404` and they returned `undefined` response at frontend. **Can you confirm this at your end?**

## Temporary Fix
A dirty fix would be to change status code to something which would not result in undefined response, like `202` and return json as `{message: 'Invalid password'}` and then you can add an if condition in `Login` page at frontend to check for it.

Here's some sample code for this.

### Frontend
#### Login.jsx
```js
...
else if (response.status === 202) {
    setError(response.data.message);
}
....
```

### Backend
#### authController.js
```js
// login 
...
const match = await bcrypt.compare(password, user.password);

if (!match) {
    const error = {
     status: 202,
     message: "Invalid password",
    };
    return next(error);
}
...
```

**Comment by numaananjum** [comment]
Hi! 
Thank you for making the effort to post a fix.  I will try this.

**Comment by numaananjum** [comment]
Hi! 
Can you please find time to post a proper fix the issue above. The issue is being generated on many EndPoint responses. 
I am building a live project so it will be massive help in terms of code quality. 

Thanks

**Comment by bug-author** [comment]
Can you provide a list of all endpoints that face this issue?

**Comment by bug-author** [comment]
fixed

**Comment by bug-author** [comment]
The fix involves two major things:

1. the interceptor now goes for the retry request only if the json response contains `"Unauthorized"` in `message` key (and all the previous conditions are still there). That means it will not be fired for the 401 response from `/login` now.

2. Previously the interceptor was suppressing the error messages and when an endpoint sent some response with status code like `401`, `403`, `404`, `500` etc. it was turned to undefined. Now if the error is not for interceptor, it throws that error which gets handled without issues.

**Comment by bug-author** [comment]
Let me know if the fix works and I'll merge the code in main branch.

**Comment by numaananjum** [comment]
Hello!

i tried to use the updated code from here.  Not sure where to pull the latest code from as i am not good with Github. here is the code that i get from now. Is that the latest code.if it is then i am still facing the same issue. It throghs "UnAuthroized" error.


api.interceptors.response.use(
  (config) => config,
  async (error) => {
    const originalReq = error.config;

    if (
      (error.response.status === 401 || error.response.status === 500) &&
      originalReq &&
      !originalReq._isRetry
    ) {
      originalReq.isRetry = true;

      try {
        await axios.get(`${process.env.REACT_APP_INTERNAL_API_PATH}/refresh`, {
          withCredentials: true,
        });

        return api.request(originalReq);
      } catch (error) {
        return error;
      }
    }
  }
);

**Comment by bug-author** [comment]
No this is not the latest code.

You need to switch to `fix/interceptor-suppressing-errors` branch using either `git checkout` or if youre using vscode then you can use the integrated source control tool. This [doc](https://code.visualstudio.com/docs/sourcecontrol/overview) can be helpful.

**Comment by numaananjum** [comment]
I works, Thanks. 

I need your help in my project for a couple of hours. Can you please reach me at numi.daska@gmail.com? 
We can discuss your hourly rates.

Thanks
